# Generated by Django 2.2.9 on 2020-04-03 13:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0008_auto_20200331_1950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dislikes',
            new_name='Dislike',
        ),
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
