# Generated by Django 2.2.8 on 2020-04-03 16:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0009_auto_20200403_1646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilePicture',
            new_name='Profile_picture',
        ),
    ]
