# Generated by Django 2.2.8 on 2020-04-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_auto_20200403_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile-pictures'),
        ),
        migrations.DeleteModel(
            name='Profile_picture',
        ),
    ]
